server:
  port: 8092

spring:
  datasource:
    url: jdbc:postgresql://localhost:15432/candidate
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        default_schema: candidate
        show_sql: true
        format_sql: true
        highlight_sql: true
      org.hibernate.envers:
        autoRegisterListeners: true
        audit_table_suffix: _history
        default_schema: candidate_history
        store_data_at_delete: true
        revision_field_name: revision
        revision_type_field_name: revision_type
        revision_sequence_name: candidate_history.revinfo_seq
    database-platform: org.hibernate.dialect.PostgreSQLDialect

#  flyway:
#    enabled: true
#    baseline-on-migrate: true
#    schemas: candidate,candidate_history
#    locations: classpath:db/migration

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: true
        spring.json.type.mapping: candidateCreated:com.example.event.CandidateCreatedEvent

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus

otel:
  exporter:
    otlp:
      endpoint: http://localhost:4318
      protocol: http/protobuf
  logs:
    exporter: none
  metrics:
    exporter: none