services:
  calculation-service:
    build:
      context: ./
    ports:
      - "8094:8094"
    environment:
      SPRING_KAFKA_BOOTSTRAP-SERVERS: kafka:9092
      SPRING_REDIS_HOST: redis_container
    networks:
      - pet_shared-network

networks:
  pet_shared-network:
    external: true
    name: pet_shared-network